#!/bin/bash

# generates site for gh-pages and commits to the local branch
# note: changes current branch to gh-pages

die() { echo "error: $@" >&2; exit 1; }
cd "$(dirname "$0")"
head="$(git rev-parse --short HEAD)"
ROUTER_BASE=/beer/ yarn generate || die "failed to generate"
git checkout gh-pages || die "checkout failed, repo is probably dirty"
git ls-files | grep -v ^\.gitignore | xargs -n 1 git rm
rsync -a dist/ . || die "rsync failed"
[[ -n "$(git status -s)" ]] || die "generated site has no changes"
git add . && git commit -am "Generate gh-pages for $head" || die "couldn't write commit"
echo "checked out gh-pages branch and committed updates, push when ready"
